/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorLogin;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Intr4Snak3
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        FrmPrincipal.jdpPrincipal.setBackground(Color.LIGHT_GRAY);
        
        
        lbFecha.setText(fecha());
        lbUsuario.setText(FrmLogin.txtUsuario.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        jmAgregarAlumno = new javax.swing.JMenuItem();
        jmListadoAlumnos = new javax.swing.JMenuItem();
        menuRegistros = new javax.swing.JMenu();
        jmAgregarRegistro = new javax.swing.JMenuItem();
        jmInformeRegistro = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        jmAgregarUsuario = new javax.swing.JMenuItem();
        jmListadoUsuarios = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jmAcercaDe = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido al Registro PsicoSocial");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("FECHA:");

        lbFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbFecha.setText("DD/MM/YYYY");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("USUARIO:");

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbUsuario.setText("USUARIO");

        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lbFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPrincipal.setLayer(lbUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1)
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsuario)
                    .addComponent(lbFecha))
                .addGap(108, 108, 108))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuAlumnos.setText("Alumnos");

        jmAgregarAlumno.setText("Agregar");
        jmAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarAlumnoActionPerformed(evt);
            }
        });
        menuAlumnos.add(jmAgregarAlumno);

        jmListadoAlumnos.setText("Listado Alumnos");
        menuAlumnos.add(jmListadoAlumnos);

        jMenuBar1.add(menuAlumnos);

        menuRegistros.setText("Registros");

        jmAgregarRegistro.setText("Agregar");
        menuRegistros.add(jmAgregarRegistro);

        jmInformeRegistro.setText("Informe Registros");
        menuRegistros.add(jmInformeRegistro);

        jMenuBar1.add(menuRegistros);

        menuUsuarios.setText("Usuarios");

        jmAgregarUsuario.setText("Agregar");
        menuUsuarios.add(jmAgregarUsuario);

        jmListadoUsuarios.setText("Listado Usuarios");
        menuUsuarios.add(jmListadoUsuarios);

        jMenuBar1.add(menuUsuarios);

        menuAyuda.setText("Ayuda");

        jmAcercaDe.setText("Acerca de...");
        menuAyuda.add(jmAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAgregarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     * @return
     */
    public static String fecha() {
        LocalDate hoy = LocalDate.now();
        LocalTime ahora = LocalTime.now();
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

        LocalDateTime fecha = LocalDateTime.of(hoy, ahora);
        String fechaFormateada = fecha.format(formatoFecha);

        return fechaFormateada;
    }

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public static javax.swing.JDesktopPane jdpPrincipal;
    public javax.swing.JMenuItem jmAcercaDe;
    public javax.swing.JMenuItem jmAgregarAlumno;
    public javax.swing.JMenuItem jmAgregarRegistro;
    public javax.swing.JMenuItem jmAgregarUsuario;
    public javax.swing.JMenuItem jmInformeRegistro;
    public javax.swing.JMenuItem jmListadoAlumnos;
    public javax.swing.JMenuItem jmListadoUsuarios;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbUsuario;
    public javax.swing.JMenu menuAlumnos;
    public javax.swing.JMenu menuAyuda;
    public javax.swing.JMenu menuRegistros;
    public javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
